/// Lớp tiện ích hỗ trợ đa ngôn ngữ cho SOS Care
class Localization {
  static String currentLanguage = 'vi'; // 'vi' hoặc 'en'

  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'appName': 'SOS Care',
      'login': 'Đăng nhập',
      'register': 'Đăng ký',
      'fillAllFields': 'Vui lòng nhập đầy đủ thông tin',
      'username': 'Tên tài khoản',
      'email': 'Email',
      'password': 'Mật khẩu',
      'confirmPassword': 'Xác nhận mật khẩu',
      'invalidEmail': 'Email không đúng định dạng',
      'passwordMismatch': 'Mật khẩu xác nhận không khớp',
      'emailOrUsername': 'Email / Tên tài khoản',
      'rememberMe': 'Ghi nhớ đăng nhập',
      'noAccount': 'Chưa có tài khoản?',
      'registerNow': 'Đăng ký ngay',
      'haveAccount': 'Đã có tài khoản?',
      'loginNow': 'Đăng nhập ngay',
      'welcome': 'Chào mừng',
      'safetyOverview': 'Tổng quan an toàn',
      'relativeList': 'Danh sách người thân',
      'noRelatives': 'Chưa có người thân nào',
      'noRelativesHint': 'Bấm nút bên dưới để thêm người thân đầu tiên',
      'addFirstRelative': 'Thêm người thân đầu tiên',
      'battery': 'Pin',
      'lastUpdate': 'Cập nhật',
      'statusSafeText': 'Bình thường',
      'statusWarningText': 'Cảnh báo',
      'statusCriticalText': 'Khẩn cấp',
      'callElderly': 'Gọi điện',
      'listenAmbient': 'Nghe xung quanh',
      'ringDevice': 'Bật chuông',
      'sendSOSMsg': 'Nhắn khẩn cấp',
      'warningHistory': 'Lịch sử sự cố SOS',
      'healthMetrics': 'Chỉ số sức khỏe',
      'heartRate': 'Nhịp tim',
      'spo2': 'Nồng độ SpO2',
      'fallDetection': 'Phát hiện té ngã',
      'gpsStatus': 'Trạng thái GPS',
      'deviceStatus': 'Trạng thái thiết bị',
      'wearableDevice': 'Thiết bị đeo',
      'safeZone': 'Vùng an toàn',
      'settings': 'Cài đặt',
      'manageRelatives': 'Quản lý người thân',
      'deleteRelative': 'Xóa người thân',
      'editRelativeInfo': 'Chỉnh sửa thông tin người thân',
      'editInfo': 'Chỉnh sửa thông tin',
      'addContactHint': 'Thêm liên hệ mới',
      'contactName': 'Tên người liên hệ',
      'invalidPhone': 'SĐT phải đúng 10 chữ số',
      'deleteRelativeConfirm': 'Bạn có chắc chắn muốn xóa người thân này khỏi danh sách?',
      'deleteRelativeSuccess': 'Đã xóa người thân',
      'deleteRelativeFailed': 'Không thể xóa',
      'delete': 'Xóa',
      'emergencyContacts': 'Số khẩn cấp',
      'autoCall': 'Tự động gọi khi không phản hồi',
      'soundAlert': 'Âm thanh cảnh báo',
      'darkMode': 'Chế độ tối',
      'language': 'Ngôn ngữ',
      'selectLanguage': 'Chọn ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'logout': 'Đăng xuất',
      'confirmAlert': 'Xác nhận đã nhận cảnh báo',
      'needsHelp': 'cần hỗ trợ!',
      'location': 'Vị trí',
      'time': 'Thời gian',
      'urgency': 'Mức độ khẩn cấp',
      'navigateQuick': 'Chỉ đường nhanh',
      'statusOnline': 'Kết nối',
      'statusOffline': 'Mất kết nối',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'unprocessed': 'CHƯA XỬ LÝ',
      'processed': 'ĐÃ XỬ LÝ',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'add': 'Thêm mới',
      'success': 'Thành công',
      'error': 'Lỗi',
      'active': 'Đang hoạt động',
      'inactive': 'Ngừng hoạt động',
      'home': 'Trang chủ',
      'alerts': 'Cảnh báo',
      'noAlerts': 'Không có cảnh báo nào.',
      'account': 'Tài khoản',
      'profile': 'Thông tin cá nhân',
      'mapViewTitle': 'Vị trí của',
      'mapUpdatedJustNow': 'Vừa cập nhật',
      'mapUpdatedMinutes': 'Cập nhật {n} phút trước',
      'mapUpdatedHours': 'Cập nhật {n} giờ trước',
      'mapUpdatedAt': 'Vị trí lúc {t}',
      'mapJustNow': 'Vừa xong',
      'quickCall': 'Gọi',
      'quickListen': 'Nghe',
      'quickRing': 'Bật chuông',
      'quickSms': 'Nhắn tin',
      'mapMinutesAgo': '{n} phút trước',
      'mapHoursAgo': '{n} giờ trước',
      'mapAccuracy': 'Sai số ±{m} m',
      'mapCurrentLocation': 'VỊ TRÍ HIỆN TẠI',
      'mapLastLocation': 'VỊ TRÍ CUỐI CÙNG',
      'mapIncidentLocation': 'VỊ TRÍ SỰ CỐ',
      'mapWaitingGps': 'Chưa có vị trí',
      'mapWaitingGpsDesc': 'Thiết bị của {name} chưa gửi tọa độ. Vị trí sẽ hiện ngay khi nhận được.',
      'mapOfflineNote': 'Thiết bị đeo không gửi dữ liệu. Người thân có thể đã di chuyển khỏi vị trí này.',
      'mapAddressLoading': 'Đang tìm địa chỉ…',
      'mapFollowing': 'Đang bám theo vị trí',
      'mapBackToPerson': 'Về vị trí hiện tại',
      'mapFitAll': 'Xem cả nhà và sự cố',
      'mapHome': 'Nhà',
      'mapOpen': 'Mở bản đồ',
      'mapCall': 'Gọi',
      'mapRing': 'Bật chuông thiết bị',
      'mapRingOffline': 'Thiết bị mất kết nối, không bật chuông được',
      'mapDirections': 'Chỉ đường',
      'mapDirectionsHere': 'Chỉ đường tới đây',
      'mapNoContact': 'Chưa có số liên hệ khẩn cấp',
      'mapNoHome': 'Chưa đặt vị trí nhà',
      'mapNoHomeDesc': 'Dùng để chỉ đường về nhà khi có SOS',
      'mapSetHomeNow': 'Đặt ngay',
      'mapSosTitle': 'SOS · {name} cần giúp đỡ',
      'mapSosSubtitle': 'Lúc {t}',
      'homeTitle': 'Vị trí nhà của {name}',
      'homeSearchHint': 'Tìm số nhà, tên đường…',
      'homeDragHint': 'Kéo bản đồ để ghim đúng nóc nhà',
      'homeZoomIn': 'Phóng to sát hơn để ghim chính xác',
      'homeAddressLabel': 'ĐỊA CHỈ NHÀ',
      'homeSave': 'Lưu vị trí nhà',
      'homeUseCurrent': 'Dùng vị trí hiện tại của {name} làm nhà',
      'homeNoResults': 'Không tìm thấy địa chỉ phù hợp',
      'homeSearchError': 'Không kết nối được dịch vụ tìm địa chỉ, thử lại sau',
      'homePinned': 'Vị trí đã ghim',
      'homeField': 'Vị trí nhà',
      'homeFieldHint': 'Bấm để ghim trên bản đồ',
      'homeRequired': 'Vui lòng ghim vị trí nhà',
      'homeChange': 'Đổi',
      'homeSaved': 'Đã lưu vị trí nhà',
      'homeSaveFailed': 'Lưu vị trí nhà thất bại, vui lòng thử lại',
      'healthTracking': 'Theo dõi sức khỏe',
      'emergencyContactsTitle': 'Danh bạ khẩn cấp',
      'callNow': 'Gọi ngay',
      'addContact': 'Thêm liên hệ mới',
      'sosAlerts': 'Thông báo SOS khẩn cấp',
      'safeZoneAlerts': 'Cảnh báo vùng an toàn',
      'healthReminders': 'Nhắc nhở sức khỏe',
      'firmwareUpdates': 'Cập nhật firmware',
      'changePassword': 'Đổi mật khẩu',
      'updateInfo': 'Cập nhật thông tin',
      'notificationSettings': 'Cài đặt thông báo',
      'generalSettings': 'Cài đặt chung',
      'version': 'Phiên bản',
      'termsOfService': 'Điều khoản sử dụng',
      'logoutConfirm': 'Bạn có chắc muốn đăng xuất?',
      'changeAvatar': 'Đổi ảnh',
      'tapAvatarToPickFromGallery': 'Bấm vào ảnh hoặc biểu tượng camera để chọn ảnh từ thư viện',
      'uploadingAvatar': 'Đang tải ảnh đại diện...',
      'avatarUpdated': 'Đã cập nhật ảnh đại diện',
      'title': 'Tiêu đề',
      'content': 'Nội dung',
      'level': 'Mức độ',
      'relatedPerson': 'Người liên quan',
      'saveAlert': 'Lưu cảnh báo',
      'temperature': 'Nhiệt độ',
      'bloodPressure': 'Huyết áp',
      'statusNormal': 'Bình thường',
      'directions': 'Chỉ đường',
      'sms': 'Nhắn tin',
      'listen': 'Nghe âm thanh',
      'ring': 'Rung chuông',
      'age': 'Tuổi',
      'address': 'Địa chỉ',
    },
    'en': {
      'appName': 'SOS Care',
      'login': 'Login',
      'register': 'Register',
      'fillAllFields': 'Please fill in all fields',
      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'invalidEmail': 'Invalid email format',
      'passwordMismatch': 'Password confirmation does not match',
      'emailOrUsername': 'Email / Username',
      'rememberMe': 'Remember me',
      'noAccount': 'No account?',
      'registerNow': 'Register now',
      'haveAccount': 'Already have an account?',
      'loginNow': 'Login now',
      'welcome': 'Welcome',
      'safetyOverview': 'Safety Overview',
      'relativeList': 'Relatives List',
      'noRelatives': 'No relatives yet',
      'noRelativesHint': 'Tap the button below to add your first relative',
      'addFirstRelative': 'Add first relative',
      'battery': 'Battery',
      'lastUpdate': 'Updated',
      'statusSafeText': 'Normal',
      'statusWarningText': 'Warning',
      'statusCriticalText': 'Critical',
      'callElderly': 'Call',
      'listenAmbient': 'Listen',
      'ringDevice': 'Ring Bell',
      'sendSOSMsg': 'Send SMS',
      'warningHistory': 'SOS Warning History',
      'healthMetrics': 'Health Metrics',
      'heartRate': 'Heart Rate',
      'spo2': 'SpO2 Level',
      'fallDetection': 'Fall Detection',
      'gpsStatus': 'GPS Status',
      'deviceStatus': 'Device Status',
      'wearableDevice': 'Wearable Device',
      'safeZone': 'Safe Zone',
      'settings': 'Settings',
      'manageRelatives': 'Manage Relatives',
      'deleteRelative': 'Delete relative',
      'editRelativeInfo': 'Edit relative info',
      'editInfo': 'Edit info',
      'addContactHint': 'Add new contact',
      'contactName': 'Contact name',
      'invalidPhone': 'Phone number must be exactly 10 digits',
      'deleteRelativeConfirm': 'Are you sure you want to remove this relative from the list?',
      'deleteRelativeSuccess': 'Relative removed',
      'deleteRelativeFailed': 'Could not remove relative',
      'delete': 'Delete',
      'emergencyContacts': 'Emergency Numbers',
      'autoCall': 'Auto-call on no response',
      'soundAlert': 'Alert Sound',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'logout': 'Logout',
      'confirmAlert': 'Acknowledge Alert',
      'needsHelp': 'needs assistance!',
      'location': 'Location',
      'time': 'Time',
      'urgency': 'Urgency level',
      'navigateQuick': 'Quick Navigation',
      'statusOnline': 'Online',
      'statusOffline': 'Offline',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'unprocessed': 'UNACKNOWLEDGED',
      'processed': 'ACKNOWLEDGED',
      'save': 'Save',
      'cancel': 'Cancel',
      'add': 'Add New',
      'success': 'Success',
      'error': 'Error',
      'active': 'Active',
      'inactive': 'Inactive',
      'home': 'Home',
      'alerts': 'Alerts',
      'noAlerts': 'No alerts available.',
      'account': 'Account',
      'profile': 'Profile',
      'mapViewTitle': 'Location of',
      'mapUpdatedJustNow': 'Updated just now',
      'mapUpdatedMinutes': 'Updated {n} min ago',
      'mapUpdatedHours': 'Updated {n} h ago',
      'mapUpdatedAt': 'Location at {t}',
      'mapJustNow': 'Just now',
      'quickCall': 'Call',
      'quickListen': 'Listen',
      'quickRing': 'Ring',
      'quickSms': 'Message',
      'mapMinutesAgo': '{n} min ago',
      'mapHoursAgo': '{n} h ago',
      'mapAccuracy': '±{m} m accuracy',
      'mapCurrentLocation': 'CURRENT LOCATION',
      'mapLastLocation': 'LAST KNOWN LOCATION',
      'mapIncidentLocation': 'INCIDENT LOCATION',
      'mapWaitingGps': 'No location yet',
      'mapWaitingGpsDesc': "{name}'s device hasn't sent a location yet. It will appear as soon as one arrives.",
      'mapOfflineNote': "The wearable isn't sending data. Your relative may have moved from this spot.",
      'mapAddressLoading': 'Looking up address…',
      'mapFollowing': 'Following location',
      'mapBackToPerson': 'Back to current location',
      'mapFitAll': 'Show home and incident',
      'mapHome': 'Home',
      'mapOpen': 'Open map',
      'mapCall': 'Call',
      'mapRing': 'Ring device',
      'mapRingOffline': "Device is offline and can't ring",
      'mapDirections': 'Directions',
      'mapDirectionsHere': 'Directions here',
      'mapNoContact': 'No emergency contact yet',
      'mapNoHome': 'Home location not set',
      'mapNoHomeDesc': 'Used to guide you home during an SOS',
      'mapSetHomeNow': 'Set now',
      'mapSosTitle': 'SOS · {name} needs help',
      'mapSosSubtitle': 'At {t}',
      'homeTitle': "{name}'s home",
      'homeSearchHint': 'Search house number, street…',
      'homeDragHint': 'Drag the map to pin the exact rooftop',
      'homeZoomIn': 'Zoom in closer to pin accurately',
      'homeAddressLabel': 'HOME ADDRESS',
      'homeSave': 'Save home location',
      'homeUseCurrent': "Use {name}'s current location as home",
      'homeNoResults': 'No matching address',
      'homeSearchError': "Couldn't reach the address search service, try again",
      'homePinned': 'Pinned location',
      'homeField': 'Home location',
      'homeFieldHint': 'Tap to pin on the map',
      'homeRequired': 'Please pin the home location',
      'homeChange': 'Change',
      'homeSaved': 'Home location saved',
      'homeSaveFailed': "Couldn't save home location, please try again",
      'healthTracking': 'Health Tracking',
      'emergencyContactsTitle': 'Emergency Contacts',
      'callNow': 'Call Now',
      'addContact': 'Add Contact',
      'sosAlerts': 'SOS Emergency Alerts',
      'safeZoneAlerts': 'Safe Zone Alerts',
      'healthReminders': 'Health Reminders',
      'firmwareUpdates': 'Firmware Updates',
      'changePassword': 'Change Password',
      'updateInfo': 'Update Information',
      'notificationSettings': 'Notification Settings',
      'generalSettings': 'General Settings',
      'version': 'Version',
      'termsOfService': 'Terms of Service',
      'logoutConfirm': 'Are you sure you want to logout?',
      'changeAvatar': 'Change avatar',
      'tapAvatarToPickFromGallery': 'Tap the avatar or the camera icon to pick from gallery',
      'uploadingAvatar': 'Uploading avatar...',
      'avatarUpdated': 'Avatar updated',
      'title': 'Title',
      'content': 'Content',
      'level': 'Level',
      'relatedPerson': 'Related Person',
      'saveAlert': 'Save Alert',
      'temperature': 'Temperature',
      'bloodPressure': 'Blood Pressure',
      'statusNormal': 'Normal',
      'directions': 'Directions',
      'sms': 'SMS',
      'listen': 'Listen',
      'ring': 'Ring',
      'age': 'Age',
      'address': 'Address',
    }
  };

  /// Hàm dịch chuỗi dựa trên key
  static String translate(String key) {
    return _localizedValues[currentLanguage]?[key] ?? key;
  }
}
