/// Lớp tiện ích hỗ trợ đa ngôn ngữ cho SOS Care
class Localization {
  static String currentLanguage = 'vi'; // 'vi' hoặc 'en'

  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'appName': 'SOS Care',
      'login': 'Đăng nhập',
      'register': 'Đăng ký',
      'fillAllFields': 'Vui lòng nhập đầy đủ thông tin',
      'username': 'Tên tài khoản',
      'email': 'Email',
      'password': 'Mật khẩu',
      'confirmPassword': 'Xác nhận mật khẩu',
      'invalidEmail': 'Email không đúng định dạng',
      'passwordMismatch': 'Mật khẩu xác nhận không khớp',
      'emailOrUsername': 'Email / Tên tài khoản',
      'rememberMe': 'Ghi nhớ đăng nhập',
      'noAccount': 'Chưa có tài khoản?',
      'registerNow': 'Đăng ký ngay',
      'haveAccount': 'Đã có tài khoản?',
      'loginNow': 'Đăng nhập ngay',
      'welcome': 'Chào mừng',
      'safetyOverview': 'Tổng quan an toàn',
      'relativeList': 'Danh sách người thân',
      'noRelatives': 'Chưa có người thân nào',
      'noRelativesHint': 'Bấm nút bên dưới để thêm người thân đầu tiên',
      'addFirstRelative': 'Thêm người thân đầu tiên',
      'battery': 'Pin',
      'lastUpdate': 'Cập nhật',
      'statusSafeText': 'Bình thường',
      'statusWarningText': 'Cảnh báo',
      'statusCriticalText': 'Khẩn cấp',
      'callElderly': 'Gọi điện',
      'listenAmbient': 'Nghe xung quanh',
      'ringDevice': 'Bật chuông',
      'sendSOSMsg': 'Nhắn khẩn cấp',
      'warningHistory': 'Lịch sử sự cố SOS',
      'healthMetrics': 'Chỉ số sức khỏe',
      'heartRate': 'Nhịp tim',
      'spo2': 'Nồng độ SpO2',
      'fallDetection': 'Phát hiện té ngã',
      'gpsStatus': 'Trạng thái GPS',
      'deviceStatus': 'Trạng thái thiết bị',
      'wearableDevice': 'Thiết bị đeo',
      'safeZone': 'Vùng an toàn',
      'settings': 'Cài đặt',
      'manageRelatives': 'Quản lý người thân',
      'deleteRelative': 'Xóa người thân',
      'deleteRelativeConfirm': 'Bạn có chắc chắn muốn xóa người thân này khỏi danh sách?',
      'deleteRelativeSuccess': 'Đã xóa người thân',
      'deleteRelativeFailed': 'Không thể xóa',
      'delete': 'Xóa',
      'emergencyContacts': 'Số khẩn cấp',
      'autoCall': 'Tự động gọi khi không phản hồi',
      'soundAlert': 'Âm thanh cảnh báo',
      'darkMode': 'Chế độ tối',
      'language': 'Ngôn ngữ',
      'selectLanguage': 'Chọn ngôn ngữ',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'logout': 'Đăng xuất',
      'confirmAlert': 'Xác nhận đã nhận cảnh báo',
      'needsHelp': 'cần hỗ trợ!',
      'location': 'Vị trí',
      'time': 'Thời gian',
      'urgency': 'Mức độ khẩn cấp',
      'navigateQuick': 'Chỉ đường nhanh',
      'statusOnline': 'Kết nối',
      'statusOffline': 'Mất kết nối',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'unprocessed': 'CHƯA XỬ LÝ',
      'processed': 'ĐÃ XỬ LÝ',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'add': 'Thêm mới',
      'success': 'Thành công',
      'error': 'Lỗi',
      'active': 'Đang hoạt động',
      'inactive': 'Ngừng hoạt động',
      'home': 'Trang chủ',
      'alerts': 'Cảnh báo',
      'noAlerts': 'Không có cảnh báo nào.',
      'account': 'Tài khoản',
      'profile': 'Thông tin cá nhân',
      'mapViewTitle': 'Vị trí của',
      'healthTracking': 'Theo dõi sức khỏe',
      'emergencyContactsTitle': 'Danh bạ khẩn cấp',
      'callNow': 'Gọi ngay',
      'addContact': 'Thêm liên hệ mới',
      'sosAlerts': 'Thông báo SOS khẩn cấp',
      'safeZoneAlerts': 'Cảnh báo vùng an toàn',
      'healthReminders': 'Nhắc nhở sức khỏe',
      'firmwareUpdates': 'Cập nhật firmware',
      'changePassword': 'Đổi mật khẩu',
      'updateInfo': 'Cập nhật thông tin',
      'notificationSettings': 'Cài đặt thông báo',
      'generalSettings': 'Cài đặt chung',
      'version': 'Phiên bản',
      'termsOfService': 'Điều khoản sử dụng',
      'logoutConfirm': 'Bạn có chắc muốn đăng xuất?',
      'changeAvatar': 'Đổi ảnh',
      'tapAvatarToPickFromGallery': 'Bấm vào ảnh để chọn từ thư viện',
      'title': 'Tiêu đề',
      'content': 'Nội dung',
      'level': 'Mức độ',
      'relatedPerson': 'Người liên quan',
      'saveAlert': 'Lưu cảnh báo',
      'temperature': 'Nhiệt độ',
      'bloodPressure': 'Huyết áp',
      'statusNormal': 'Bình thường',
      'directions': 'Chỉ đường',
      'sms': 'Nhắn tin',
      'listen': 'Nghe âm thanh',
      'ring': 'Rung chuông',
      'age': 'Tuổi',
      'address': 'Địa chỉ',
    },
    'en': {
      'appName': 'SOS Care',
      'login': 'Login',
      'register': 'Register',
      'fillAllFields': 'Please fill in all fields',
      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'invalidEmail': 'Invalid email format',
      'passwordMismatch': 'Password confirmation does not match',
      'emailOrUsername': 'Email / Username',
      'rememberMe': 'Remember me',
      'noAccount': 'No account?',
      'registerNow': 'Register now',
      'haveAccount': 'Already have an account?',
      'loginNow': 'Login now',
      'welcome': 'Welcome',
      'safetyOverview': 'Safety Overview',
      'relativeList': 'Relatives List',
      'noRelatives': 'No relatives yet',
      'noRelativesHint': 'Tap the button below to add your first relative',
      'addFirstRelative': 'Add first relative',
      'battery': 'Battery',
      'lastUpdate': 'Updated',
      'statusSafeText': 'Normal',
      'statusWarningText': 'Warning',
      'statusCriticalText': 'Critical',
      'callElderly': 'Call',
      'listenAmbient': 'Listen',
      'ringDevice': 'Ring Bell',
      'sendSOSMsg': 'Send SMS',
      'warningHistory': 'SOS Warning History',
      'healthMetrics': 'Health Metrics',
      'heartRate': 'Heart Rate',
      'spo2': 'SpO2 Level',
      'fallDetection': 'Fall Detection',
      'gpsStatus': 'GPS Status',
      'deviceStatus': 'Device Status',
      'wearableDevice': 'Wearable Device',
      'safeZone': 'Safe Zone',
      'settings': 'Settings',
      'manageRelatives': 'Manage Relatives',
      'deleteRelative': 'Delete relative',
      'deleteRelativeConfirm': 'Are you sure you want to remove this relative from the list?',
      'deleteRelativeSuccess': 'Relative removed',
      'deleteRelativeFailed': 'Could not remove relative',
      'delete': 'Delete',
      'emergencyContacts': 'Emergency Numbers',
      'autoCall': 'Auto-call on no response',
      'soundAlert': 'Alert Sound',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'vietnamese': 'Tiếng Việt',
      'english': 'English',
      'logout': 'Logout',
      'confirmAlert': 'Acknowledge Alert',
      'needsHelp': 'needs assistance!',
      'location': 'Location',
      'time': 'Time',
      'urgency': 'Urgency level',
      'navigateQuick': 'Quick Navigation',
      'statusOnline': 'Online',
      'statusOffline': 'Offline',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'unprocessed': 'UNACKNOWLEDGED',
      'processed': 'ACKNOWLEDGED',
      'save': 'Save',
      'cancel': 'Cancel',
      'add': 'Add New',
      'success': 'Success',
      'error': 'Error',
      'active': 'Active',
      'inactive': 'Inactive',
      'home': 'Home',
      'alerts': 'Alerts',
      'noAlerts': 'No alerts available.',
      'account': 'Account',
      'profile': 'Profile',
      'mapViewTitle': 'Location of',
      'healthTracking': 'Health Tracking',
      'emergencyContactsTitle': 'Emergency Contacts',
      'callNow': 'Call Now',
      'addContact': 'Add Contact',
      'sosAlerts': 'SOS Emergency Alerts',
      'safeZoneAlerts': 'Safe Zone Alerts',
      'healthReminders': 'Health Reminders',
      'firmwareUpdates': 'Firmware Updates',
      'changePassword': 'Change Password',
      'updateInfo': 'Update Information',
      'notificationSettings': 'Notification Settings',
      'generalSettings': 'General Settings',
      'version': 'Version',
      'termsOfService': 'Terms of Service',
      'logoutConfirm': 'Are you sure you want to logout?',
      'changeAvatar': 'Change avatar',
      'tapAvatarToPickFromGallery': 'Tap the avatar to pick from gallery',
      'title': 'Title',
      'content': 'Content',
      'level': 'Level',
      'relatedPerson': 'Related Person',
      'saveAlert': 'Save Alert',
      'temperature': 'Temperature',
      'bloodPressure': 'Blood Pressure',
      'statusNormal': 'Normal',
      'directions': 'Directions',
      'sms': 'SMS',
      'listen': 'Listen',
      'ring': 'Ring',
      'age': 'Age',
      'address': 'Address',
    }
  };

  /// Hàm dịch chuỗi dựa trên key
  static String translate(String key) {
    return _localizedValues[currentLanguage]?[key] ?? key;
  }
}
